const proyects = [
  {
    id: 1,
    left: true,
    images: "anima3.jpeg",
    title_2: "Anima",
    title: "Anima",
    font_title: "one",
    link_content: "Anima",

    content: [
      {
        id: 2,
        video: true,
        format: "mp4",
        link: "147079746_477523560301451_6973711631565693795_n.mp4",
        ratio: "16by9",
      },
      {
        id: 4,
        video: true,
        format: "mp4",
        link: "VÃ­deo salto.mp4",
        ratio: "4by5",
        size: "right",
      },
      { id: 6, video: false, link: "Anima16.50.07.jpeg", ratio: "6by4" },
      {
        id: 1,
        video: true,
        format: "mp4",
        link: "Anima Vuelta.mp4",
        ratio: "6by4",
        size: "left",
      },
      { id: 5, video: false, link: "Anima16.50.06.jpeg", ratio: "6by4" },
      {
        id: 3,
        video: false,
        link: "Anima16.50.05.jpeg",
        ratio: "10by15",
        size: "small",
        heightBackground: 59,
      },
      {
        id: 7,
        video: false,
        link: "Anima16.50.13.jpeg",
        ratio: "10by15",
        size: "right",
      },
    ],
  },
  {
    id: 2,
    left: true,
    images: "topm5.JPG",
    title_2: "Top Mega",
    title: "Top<br/>Me<br/>ga",
    font_title: "two",
    link_content: "Top Mega",
    content: [
      {
        id: 1,
        video: true,
        format: "mp4",
        link: "1 - Movilidad elÃ©ctrica.mp4",
        ratio: "16by9",
      },
      {
        id: 6,
        video: true,
        format: "mp4",
        link: "78463527_221328479002878_7196983808310319985_n.mp4",
        ratio: "4by5",
        size: "right",
      },

      {
        id: 3,
        video: true,
        format: "mp4",
        link: "Congelada.mp4",
        ratio: "4by7",
        size: "left2",
      },
      {
        id: 2,
        video: true,
        format: "mp4",
        link: "aparicion.mp4",
        ratio: "11by20",
        size: "right2",
      },
      {
        id: 7,
        video: true,
        format: "mp4",
        link: "Verano Topmega.mp4",
        ratio: "16by9",
      },
      {
        id: 9,
        video: false,
        link: "66443326_674771302998598_9113180442907453266_n.jpg",
        ratio: "4by5",
        size: "left",
        size: "small",
        heightBackground: 42,
      },
      {
        id: 5,
        video: true,
        format: "mp4",
        link: "Hombre  foto 3D.mp4",
        ratio: "4by7",
        size: "right",
      },
      {
        id: 4,
        video: true,
        format: "mp4",
        link: "DSC_0083.mp4",
        ratio: "11by20",
        size: "left2",
      },
      {
        id: 8,
        video: false,
        link: "68799980_410325719687999_8450999912694957348_n.jpg",
        ratio: "6by4",
      },
      {
        id: 10,
        video: false,
        link: "Captura de Pantalla 2021-11-12 a la(s) 14.03.50.png",
        ratio: "18by21",
        size: "right",
      },
    ],
  },
  {
    id: 3,
    left: false,
    images: "harlemsport1.jpg",
    title_2: "Harlem Sportswear",
    title: "Har<br/>lem<br/> Spor<br/>ts<br/>we<br/>ar",
    font_title: "three",
    link_content: "Harlem Sportswear",
    content: [
      {
        id: 1,
        video: false,
        link: "DSC_0025.jpg",
        ratio: "6by4",
      },
      {
        id: 3,
        video: false,
        link: "DSC_0042.jpg",
        ratio: "6by4",
        size: "small",
        heightBackground: 26,
      },
      {
        id: 2,
        video: false,
        link: "DSC_0059.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 5,
        video: false,
        link: "DSC_0039.jpg",
        ratio: "16by9",
        ratio: "6by4",
      },
      {
        id: 6,
        video: false,
        link: "DSC_0026.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0059-2.jpg",
        ratio: "6by4",
      },
      {
        id: 8,
        video: false,
        link: "DSC_0017.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 9,
        video: false,
        link: "DSC_0062.jpg",
        ratio: "6by4",
      },
      {
        id: 10,
        video: false,
        link: "DSC_0041.jpg",
        ratio: "4by6",
        size: "right",
      },
    ],
  },
  {
    id: 4,
    left: false,
    images: "rom1.jpg",
    title_2: "La Romeria de las rosas",
    title: "Ro<br/>mer<br/>ia<br/> de<br/> las<br/> ro<br/>sas",
    font_title: "four",
    link_content: "La Romeria de las rosas",
    content: [
      {
        id: 1,
        video: true,
        format: "mp4",
        link: "116796928_970204506829246_7716625089534911811_n.mp4",
        ratio: "16by9",
      },
      {
        id: 3,
        video: false,
        link: "DSC_0635.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 2,
        video: true,
        format: "mp4",
        link: "117295766_3000103843432634_7448684303335657078_n.mp4",
        ratio: "18by12",
      },
      {
        id: 4,
        video: true,
        format: "mp4",
        link: "Trago 3.mp4",
        ratio: "18by12",
        size: "left",
      },
      {
        id: 5,
        video: true,
        format: "mp4",
        link: "Video 2.mp4",
        ratio: "16by9",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0482.jpg",
        ratio: "18by12",
        size: "small",
        heightBackground: 26,
      },
      {
        id: 6,
        video: false,
        link: "DSC_0627.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 8,
        video: false,
        link: "rom1.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 9,
        video: true,
        format: "mp4",
        link: "117370303_2971948646261337_2796349592606616744_n.mp4",
        ratio: "16by9",
      },
    ],
  },
  {
    id: 5,
    left: true,
    images: "harlem3.jpg",
    title_2: "Harlem Bar",
    title: "Ha<br/>rlem<br/> Ba<br/>r",
    font_title: "five",
    link_content: "Harlem Bar",
    content: [
      {
        id: 1,
        video: false,
        link: "DSC_0048.jpg",
        ratio: "6by4",
      },
      {
        id: 2,
        video: false,
        link: "harlem3.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 3,
        video: false,
        link: "DSC_0155.jpg",
        ratio: "6by4",
      },
      {
        id: 4,
        video: false,
        link: "DSC_0183.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 5,
        video: false,
        link: "DSC_0434.jpg",
        ratio: "6by4",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0915.jpg",
        ratio: "18by12",
        size: "small",
        heightBackground: 26,
      },
      {
        id: 6,
        video: false,
        link: "DSC_0728.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 8,
        video: false,
        link: "harlem1.jpg",
        ratio: "4by6",
        size: "left",
      },
    ],
  },
  {
    id: 6,
    left: false,
    images: "aljibe3.jpg",
    title_2: "El aljibe de Mendez",
    title: "El aljibe<br/> de Mendez",
    font_title: "six",
    link_content: "El aljibe de Mendez",
    content: [
      {
        id: 1,
        video: true,
        format: "mp4",
        link: "Video Alji pre cumple.mp4",
        ratio: "16by9",
      },
      {
        id: 2,
        video: true,
        format: "mp4",
        link: "Marva trago 2.mp4",
        ratio: "1by1",
        size: "right",
      },
      {
        id: 3,
        video: false,
        link: "aljibe1.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 4,
        video: false,
        link: "DSC_0106.jpg",
        ratio: "4by6",
        size: "right2",
      },
      {
        id: 5,
        video: true,
        format: "mp4",
        link: "Video pos cumple alji.mp4",
        ratio: "16by9",
      },
      {
        id: 6,
        video: true,
        format: "mp4",
        link: "Video birra2.mp4",
        ratio: "4by5",
        size: "right",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0126.jpg",
        ratio: "18by12",
        size: "left",
      },
      {
        id: 8,
        video: false,
        link: "DSC_0636.jpg",
        ratio: "4by6",
        size: "right2",
      },
      {
        id: 9,
        video: true,
        format: "mp4",
        link: "Trago.mp4",
        ratio: "16by9",
      },
      {
        id: 10,
        video: false,
        link: "DSC_0079.jpg",
        ratio: "18by12",
        size: "right",
      },
      {
        id: 11,
        video: false,
        link: "DSC_0626.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 12,
        video: false,
        link: "aljibe3.png",
        ratio: "20by14",
        size: "right2",
      },
      {
        id: 13,
        video: true,
        format: "mp4",
        link: "Sorteo San Valentin 2.mp4",
        ratio: "16by9",
      },
      {
        id: 14,
        video: false,
        link: "DSC_0129.jpg",
        ratio: "18by12",
        size: "right",
      },
      {
        id: 15,
        video: false,
        link: "DSC_0083.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 16,
        video: true,
        format: "mp4",
        link: "Fruta Final 2.mp4",
        ratio: "16by9",
        size: "right2",
      },
      {
        id: 17,
        video: true,
        format: "mp4",
        link: "Video Chasquido.mp4",
        ratio: "16by9",
      },
      {
        id: 18,
        video: false,
        link: "DSC_0644.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 19,
        video: false,
        link: "DSC_0640.jpg",
        ratio: "18by12",
        size: "left",
      },
    ],
  },
  {
    id: 17,
    title_2: "Shujman",
    title: "Shujman",
    font_title: "fourteen",
    images: "shujmanV1-home.jpg",
    frame: "left",
    link_content: "Shujman",
    content: [
      {
        id: 1,
        video: false,
        link: "shujmanV1-home (1).png",
        ratio: "21by16",
      },
      {
        id: 2,
        video: false,
        link: "shujmanH1.png",
        ratio: "19by9",
      },
      {
        id: 3,
        video: false,
        link: "shujmanH2.png",
        ratio: "19by9",
      },
      {
        id: 4,
        video: false,
        link: "shujmanV2.png",
        ratio: "18by12",
      },
      {
        id: 5,
        video: false,
        link: "shujmnaH3.png",
        ratio: "21by7",
      },
      {
        id: 6,
        video: false,
        link: "shujmanV3.png",
        ratio: "18by13",
      },
    ],
  },
  {
    id: 9,
    left: true,
    images: "moda2.jpg",
    title_2: "Moda 1",
    title: "Mo<br/>da<br/> 1",
    font_title: "nine",
    link_content: "Moda 1",
    content: [
      {
        id: 11,
        video: false,
        link: "DSC_0246.jpg",
        ratio: "18by12",
      },

      {
        id: 5,
        video: false,
        link: "moda2.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 3,
        video: false,
        link: "IMG_0890.jpg",
        ratio: "15by20",
        size: "left",
      },
      {
        id: 1,
        video: false,
        link: "DSC_0209.jpg",
        ratio: "4by6",
        size: "right2",
      },
      {
        id: 2,
        video: false,
        link: "DSC_0215.jpg",
        ratio: "4by6",
        size: "center",
      },
      {
        id: 6,
        video: false,
        link: "DSC_0135.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0133.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 8,
        video: false,
        link: "DSC_0127.jpg",
        ratio: "4by6",
        size: "right2",
      },
      {
        id: 9,
        video: false,
        link: "DSC_0048.jpg",
        ratio: "4by6",
        size: "center",
      },
      {
        id: 10,
        video: false,
        link: "DSC_0021.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 4,
        video: false,
        link: "moda1.jpg",
        ratio: "4by6",
        size: "left",
      },
    ],
  },

  {
    id: 7,
    left: true,
    images: "ranchov2.jpeg",
    title_2: "Rancho Viejo",
    title: "Ran<br/>cho<br/> Vie<br/>jo",
    font_title: "seven",
    link_content: "Rancho Viejo",
    content: [
      {
        id: 5,
        video: false,
        link: "WhatsApp Image 2021-01-19 at 16.15.37.jpeg",
        ratio: "18by12",
      },
      {
        id: 1,
        video: false,
        link: "139471267_2735009120145991_1222171169005844531_n.jpg",
        ratio: "4by5",
        size: "right",
      },
      {
        id: 2,
        video: false,
        link: "140207054_261690828632437_6582086430152144192_n.jpg",
        ratio: "4by5",
        size: "left",
      },
      {
        id: 3,
        video: false,
        link: "140726097_313815780070751_5727450565897206193_n.jpg",
        ratio: "4by5",
        size: "right2",
      },
      {
        id: 4,
        video: false,
        link: "146459218_257852812406906_2295490923611997037_n.jpg",
        ratio: "1by1",
      },
      {
        id: 6,
        video: false,
        link: "WhatsApp Image 2021-01-19 at 16.15.37-2.jpeg",
        ratio: "9by17",
        size: "right",
      },
      {
        id: 7,
        video: false,
        link: "WhatsApp Image 2021-01-19 at 16.16.33.jpeg",
        ratio: "4by5",
        size: "left",
      },
    ],
  },
  {
    id: 8,
    left: false,
    images: "marren2.jpg",
    title_2: "Marren",
    title: "Ma<br/>rr<br/>en",
    font_title: "eight",
    link_content: "Marren",
    content: [
      {
        id: 9,
        video: true,
        format: "mp4",
        link: "Video trago.mp4",
        ratio: "16by9",
      },

      {
        id: 2,
        video: true,
        format: "mp4",
        link: "posteo.mp4",
        ratio: "13by18",
        size: "right",
      },
      {
        id: 3,
        video: false,
        link: "Captura de Pantalla 2021-11-13 a la(s) 16.51.04.png",
        ratio: "18by12",
      },
      {
        id: 4,
        video: true,
        format: "mp4",
        link: "70600938_2284377938482312_4932871126581630255_n.mp4",
        ratio: "18by12",
        size: "left",
      },
      {
        id: 5,
        video: true,
        format: "mp4",
        link: "2x1 porron heineken.mp4",
        ratio: "16by9",
      },
      {
        id: 6,
        video: false,
        link: "DSC_0185.JPG",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0340.jpg",
        ratio: "18by12",
      },
      {
        id: 8,
        video: false,
        link: "marren1.JPG",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 1,
        video: true,
        format: "mp4",
        link: "Video burger.mp4",
        ratio: "16by9",
      },

      {
        id: 10,
        video: false,
        link: "marren2.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 11,
        video: false,
        link: "DSC_0348.jpg",
        ratio: "18by12",
      },
      {
        id: 12,
        video: false,
        link: "Captura de Pantalla 2021-11-13 a la(s) 16.56.32.png",
        ratio: "18by12",
        size: "left",
      },
    ],
  },

  {
    id: 15,
    left: true,
    images: "chacoH2-home.jpg",
    title_2: "Cenit",
    title: "Cenit",
    font_title: "seventeen",
    link_content: "Cenit",
    content: [
      {
        id: 1,
        video: false,
        link: "chacoH1.png",
        ratio: "18by9",
      },
      {
        id: 2,
        video: false,
        link: "chacoH2-home.png",
        ratio: "18by9",
      },
      {
        id: 3,
        video: false,
        link: "chacoH3.png",
        ratio: "21by9",
      },
      {
        id: 4,
        video: false,
        link: "chacoH4.png",
        ratio: "18by14",
      },
      {
        id: 5,
        video: false,
        link: "chacoH5.png",
        ratio: "18by9",
      },
      {
        id: 6,
        video: false,
        link: "chacoHV2.png",
        ratio: "21by16",
      },
      {
        id: 7,
        video: false,
        link: "chacoV1-home.png",
        ratio: "18by12",
      },
      {
        id: 8,
        video: false,
        link: "chacoV4.png",
        ratio: "18by14",
      },
    ],
  },
  {
    id: 12,
    left: true,
    images: "mirasoles1.jpg",
    title_2: "NUT Mirasoles",
    title: "NUT<br/> Mira<br/>so<br/>les",
    font_title: "twelve",
    link_content: "NUT Mirasoles",
    content: [
      {
        id: 1,
        video: false,
        link: "DSC_0091.jpg",
        ratio: "18by12",
      },
      {
        id: 3,
        video: false,
        link: "DSC_0475.jpg",
        ratio: "18by12",
        size: "small",
        heightBackground: 27,
      },
      {
        id: 2,
        video: false,
        link: "DSC_0457.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 4,
        video: false,
        link: "DSC_0468.jpg",
        ratio: "18by21",
        size: "left",
      },
      {
        id: 5,
        video: false,
        link: "DSC_0297.jpg",
        ratio: "18by12",
      },
      {
        id: 7,
        video: false,
        link: "DSC_0305.jpg",
        ratio: "18by12",
        size: "small",
        heightBackground: 27,
      },
      {
        id: 6,
        video: false,
        link: "DSC_0300.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 8,
        video: false,
        link: "mirasoles1.jpg",
        ratio: "4by6",
        size: "left",
      },
      {
        id: 9,
        video: false,
        link: "nut1.jpg",
        ratio: "18by12",
      },
      {
        id: 10,
        video: false,
        link: "DSC_0458.jpg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 11,
        video: false,
        link: "DSC_0074.jpg",
        ratio: "21by16",
      },
      {
        id: 12,
        video: false,
        link: "DSC_0079.jpg",
        ratio: "18by12",
        size: "left",
      },
      {
        id: 13,
        video: false,
        link: "DSC_0395-2B.jpg",
        ratio: "18by12",
      },
    ],
  },

  {
    id: 10,
    left: true,
    images: "somosc1.jpg",
    title_2: "Somos Chola",
    title: "So<br/>mos<br/> Cho<br/>la",
    font_title: "ten",
    link_content: "Somos Chola",
    content: [
      {
        id: 6,
        video: false,
        link: "Captura de Pantalla 2022-03-04 a la(s) 17.47.30.png",
        ratio: "18by12",
      },
      {
        id: 3,
        video: false,
        link: "62020754_2558007860877701_5768903775727970942_n.jpg",
        ratio: "4by5",
        size: "small",
        heightBackground: 59,
      },
      {
        id: 2,
        video: false,
        link: "61803855_402299143830466_5598762925834198496_n.jpg",
        ratio: "4by5",
        size: "right",
      },
      {
        id: 4,
        video: false,
        link: "62265504_165890817775233_7368060481415537556_n.jpg",
        ratio: "4by5",
        size: "left",
      },
      {
        id: 5,
        video: false,
        link: "somosc1.jpg",
        ratio: "4by5",
        size: "center",
      },
      {
        id: 1,
        video: false,
        link: "61482136_127057681836568_3119390946019517170_n.jpg",
        ratio: "4by5",
        size: "right",
      },
    ],
  },
  {
    id: 14,
    left: true,
    title_2: "Chaco",
    images: "chacoV1-home.png",
    title: "Ministerio de empleo del chaco",
    font_title: "nineteen",
    link_content: "Chaco",
    content: [
      {
        id: 1,
        video: false,
        link: "chacoH1.png",
        ratio: "18by9",
      },
      {
        id: 2,
        video: false,
        link: "chacoH2-home.png",
        ratio: "18by9",
      },
      {
        id: 3,
        video: false,
        link: "chacoH3.png",
        ratio: "21by9",
      },
      {
        id: 4,
        video: false,
        link: "chacoH4.png",
        ratio: "18by14",
      },
      {
        id: 5,
        video: false,
        link: "chacoH5.png",
        ratio: "18by9",
      },
      {
        id: 6,
        video: false,
        link: "chacoHV2.png",
        ratio: "21by16",
      },
      {
        id: 7,
        video: false,
        link: "chacoV1-home.png",
        ratio: "18by12",
      },
      {
        id: 8,
        video: false,
        link: "chacoV4.png",
        ratio: "18by14",
      },
    ],
  },
  {
    id: 16,
    left: false,
    title_2: "Lavazza",
    title: "La<br/>va<br/>zza",
    images: "lavazzaV1.jpg",
    font_title: "twelve",
    link_content: "Lavazza",
    content: [
      {
        id: 1,
        video: false,
        link: "lavazzaV1.jpg",
        ratio: "18by21",
      },
      {
        id: 2,
        video: false,
        link: "lavazzaH2.png",
        ratio: "18by9",
      },
      {
        id: 3,
        video: false,
        link: "lavazzaV2.png",
        ratio: "18by13",
      },
      {
        id: 4,
        video: false,
        link: "lavazzaH1.png",
        ratio: "18by9",
      },
      {
        id: 5,
        video: false,
        link: "lavazzaH3-home (1).png",
        ratio: "21by10",
      },
    ],
  },
  {
    id: 13,
    left: false,
    title_2: "Misia",
    title: "Misia",
    images: "misiaV1-home.png",
    font_title: "seventeen",
    link_content: "Misia",
    content: [
      {
        id: 1,
        video: false,
        link: "misiaV1-home (1).png",
        ratio: "18by13",
      },
      {
        id: 2,
        video: false,
        link: "misiaH1.png",
        ratio: "21by10",
      },
      {
        id: 3,
        video: false,
        link: "misiah2.png",
        ratio: "18by9",
      },
      {
        id: 4,
        video: false,
        link: "misiaV3.png",
        ratio: "1by1",
      },
      {
        id: 5,
        video: false,
        link: "misiaH3.png",
        ratio: "18by9",
      },
    ],
  },

  {
    id: 11,
    left: false,
    images: "WhatsApp Image 2019-01-08 at 22.09.32-4.jpeg",
    title_2: "Paprika",
    title: "Paprika",
    font_title: "eleven",
    link_content: "Paprika",
    content: [
      {
        id: 1,
        video: false,
        object_fit: "contain",
        link: "paprika1.jpeg",
        ratio: "21by13",
      },
      {
        id: 2,
        video: false,
        object_fit: "contain",
        link: "paprika2.jpeg",
        ratio: "4by6",
        size: "right",
      },
      {
        id: 3,
        video: false,
        object_fit: "contain",
        link: "WhatsApp Image 2019-01-08 at 22.09.32-3.jpeg",
        ratio: "18by15",
        size: "center2",
      },
      {
        id: 4,
        video: false,
        object_fit: "contain",
        link: "WhatsApp Image 2019-01-08 at 22.09.32-4.jpeg",
        ratio: "18by12",
        size: "left",
      },
      {
        id: 5,
        video: false,
        object_fit: "contain",
        link: "WhatsApp Image 2019-01-08 at 22.09.32-5.jpeg",
        ratio: "16by9",
      },
      {
        id: 6,
        video: false,
        link: "WhatsApp Image 2019-01-08 at 22.10.00.jpeg",
        ratio: "20by16",
        size: "right",
      },
    ],
  },
];

export { proyects };
