const data = [
  {
    proyects: [
      {
        title: "Anima",
        id: 1,
        image: "anima3.jpeg",
        font_title: "one",
        frame: "left",
        text: "Anima",
      },
      {
        title: "Top Mega",
        id: 2,
        image: "topm5.JPG",
        font_title: "two",
        text: "Top<br/>Me<br/>ga",
        frame: "left",
      },
      {
        title: "Harlem Sportswear",
        id: 3,
        image: "harlemsport1.jpg",
        font_title: "three",
        frame: "right",
        text: "Har<br/>lem<br/> Spor<br/>ts<br/>we<br/>ar",
      },
      {
        title: "Romeria de las rosas",
        id: 4,
        image: "rom1.jpg",
        font_title: "four",
        text: "Ro<br/>mer<br/>ia<br/> de<br/> las<br/> ro<br/>sas",
        frame: "right",
      },
      {
        title: "Harlem Bar",
        id: 5,
        image: "harlem3.jpg",
        font_title: "five",
        text: "Ha<br/>rlem<br/> Ba<br/>r",
        frame: "left",
      },
      {
        title: "El aljibe de Mendez",
        id: 6,
        image: "aljibe3.png",
        font_title: "six",
        text: "El aljibe<br/> de Mendez",
        frame: "right",
      },
      {
        title: "Shujman",
        id: 17,
        image: "shujmanV1-home.png",
        font_title: "fourteen",
        text: "Shujman",
        frame: "left",
      },
      {
        title: "Moda 1",
        id: 9,
        image: "moda2.jpg",
        font_title: "nine",
        text: "Mo<br/>da<br/> 1",
        frame: "left",
      },
      {
        title: "Rancho Viejo",
        id: 7,
        image: "ranchov2.jpeg",
        font_title: "seven",
        text: "Ran<br/>cho<br/> Vie<br/>jo",
        frame: "left",
      },
      {
        title: "Marren",
        id: 1,
        image: "marren2.jpg",
        font_title: "eight",
        text: "Ma<br/>rr<br/>en",
        frame: "right",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
      {
        title: "",
        id: 1,
        image: "",
        font_title: "",
        text: "",
        frame: "",
      },
    ],
  },
  {
    carousel: {
      1: {
        src: "/Carrusel/web 404 desarrollo web -07.png",
        text: "Planificación y creación de sitios web enfocados en la necesidad estratégica, comerciales y comunicacionales de cada cliente. Buscamos brindar una buena experiencia de navegación para los usuarios, transmitiendo de manera dinámica y practica el servicio, producto o mensaje deseado y a su vez, convertir el mismo en un recurso valioso para la marca.",
      },
    },
  },
  {
    peopel: {
      "Pedro Nassif": {
        id: 1,
        title: "AKA EL INGENIERO",
        description:
          "Prófugo de la Prisión de Corrientes.<br/> Es capaz de vulnerar cualquier sistema conectado a internet",
        img: "/people/PedroNassiff-destock2.jpg",
        frame: "left",
      },
    },
  },
];

export { data };
