import Head from "next/head";
import Header from "../src/Components/Header";
import Proyects from "../src/Components/Proyects";
import Services from "../src/Components/Servi";
import Carousel from "../src/Components/Carousel";
import About from "../src/Components/About";
import Blend from "../src/Components/Blend";
import People from "../src/Components/People";

export default function Home() {
  return (
    <div>
      <Head>
        <title>404 - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Proyects />
        <Services />
        {/* <Carousel /> */}
        <About />
        <Blend />
        <People />
      </div>
    </div>
  );
}
