import Head from "next/head";
import Header from "../src/Components/Header";
import Proyects from "../src/Components/Proyects";
import Services from "../src/Components/Services";
import Carousel from "../src/Components/Carousel";
import Carousel2 from "../src/Components/Carousel2";

import home from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>404 - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={home.containerHome}>
        <Header />
        <Proyects />
        <Services />
        {/* <Carousel /> */}
        <Carousel2 />
      </div>
    </div>
  );
}
