import { useRef, useState, useEffect } from "react";
import Head from "next/head";
import Hero from "../src/Components/Home/Hero";
import hero from "./styles.module.scss";

import ProyectList from "../src/Components/Home/ProyectList";
import Services from "../src/Components/Home/Servi";
import About from "../src/Components/Home/About";
import Blend from "../src/Components/Home/Blend";
import People from "../src/Components/Home/People";
import Layout from "../src/Components/Layout/Layout";
import CookieConsent, { Cookies, getCookieConsentValue } from "react-cookie-consent";

function Home() {
  const [btnAcceptState, setbtnAcceptState] = useState(true)
  const [btnCancel, setBtnCancel] = useState(true)
  const cookieConsentRef = useRef();
  const ref = useRef();

  const getCokkie = () => {
    let userCokie = localStorage.getItem("userSave")
      if(userCokie === "cookie") {
        setbtnAcceptState(false);
      }else{
        setbtnAcceptState(true)
      }
  }

  const aceptFunction = (acceptedByScrolling) => {
    console.log("getCookieConsentValue", getCookieConsentValue());
    let userCokie = localStorage.getItem("userSave")

    // cookieConsentRef.current.accept();
    if (userCokie !== "cookie") {
      setbtnAcceptState(true)
      localStorage.setItem('userSave', 'cookie');
    } else {
      return;
    }
  }

  const cancelFuncion = () => {
    setBtnCancel(false);
    setbtnAcceptState(false)

  }

useEffect(() => {
  getCokkie();
}, [])


  return (
    <>
      <Layout data-scroll-section>
      
     
        <Head>
          <title>404 - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo_2 (1).ico" />
        </Head>
        {btnAcceptState ? (
                <div className={`${hero["containerCookies"]} `} style={{ position: 'fixed', width: '800px'}}>
                <div className={`${hero["hero_bottom"]} `}>
                  <div
                    className={`${hero["hero_bottom__container"]} aspect_ratio aspect_ratio--16by9`}
                  >
                    <div
                      className={`${hero["hero_bottom__frame"]} ${hero["hero_bottom__frame--one"]}`}
                    ></div>
                    <div
                      className={`${hero["hero_bottom__frame"]} ${hero["hero_bottom__frame--two"]}`}
                    ></div>
        
        
                    <div
                      className={`${hero["hero_bottom__frame"]} ${hero["hero_bottom__frame--three"]} aspect_ratio__item object_fit_cover div-video`}
                    >
                      <div className={`${hero["hero_container_text"]}`}>
                        <div><h1 className={`${hero["hero_text_title"]}`}  style={{ textAlign: 'center', color: 'yellow', fontWeight: '700', fontFamily: 'Helvetica' }}>WELCOME TO OUR WORLD</h1></div>
                        <div><h2 className={`${hero["hero_text_subtitle"]}`}  style={{ textAlign: 'center',  fontWeight: '700',fontFamily: 'Helvetica'}}>AVISO DE COOKIES</h2></div>
                      </div>
                      <span className={hero["hero_container_btn"]} style={{ display: 'flex', justifyContent: ' center' }}>
                        <button
                        className={`${hero["hero_btn_ok"]}`}
                        style={{ border: "none", color: 'blue', fontWeight: '700', marginLeft: "0px", cursor: 'pointer'}}
                        onClick={aceptFunction}>OK</button>
                        <button 
                        style={{ border: "none", color: 'blue', fontWeight: '700', cursor: 'pointer'}}
                        className={`${hero["hero_btn_cancel"]}`}
                        onClick={cancelFuncion}
                        >CANCEL
                        </button>
                      </span>
                      <div style={{ }}>
                        <CookieConsent
                          ref={cookieConsentRef}
                          onAccept={(acceptedByScrolling) => {
                            if (acceptedByScrolling) {
                              // triggered if user scrolls past threshold
                            } else {
                            }
                          }}
                          cookieName="CookieConsent404"
                          style={{ visibility: 'hidden' }}
                          debug={true}
                        >
                        </CookieConsent>
                        <video
                      src="/cookies.mp4"
                      className={hero["hero_video__containerCokies"]}
                      autoPlay
                      ref={ref}
                    >
                      <source src="/cookies.mp4" type="video/mp4"></source>
                    </video>
                      </div>
                    </div>
                  </div>
                </div>
                </div>
              ) : (
                <h1></h1>
              )}
        {

      }
        <Hero />
        
        <ProyectList />
        <Services />
        <About />
        <Blend />
        <People />
        
        

      </Layout>
    </>
  );
}

export default Home;
