import { useRef, useState, useEffect } from "react";
import Head from "next/head";
import Hero from "../src/Components/Home/Hero";
import hero from "./styles.module.scss";
import { getCookies, getCookie, setCookie, deleteCookie } from 'cookies-next';
import ProyectList from "../src/Components/Home/ProyectList";
import Services from "../src/Components/Home/Servi";
import About from "../src/Components/Home/About";
import Blend from "../src/Components/Home/Blend";
import People from "../src/Components/Home/People";
import Layout from "../src/Components/Layout/Layout";
import CookieConsent, { Cookies, getCookieConsentValue } from "react-cookie-consent";
function Home(props) {
  const [btnAcceptState, setbtnAcceptState] = useState(true)
  const [btnCancel, setBtnCancel] = useState(true)
  const cookieConsentRef = useRef();
  const ref = useRef();

  const getCokkie = () => {
    let id = getCookie('key')
    if (id =='somos404'){
      console.log("key====", id);
      setbtnAcceptState(false);
    }
  }

  const aceptFunction = (acceptedByScrolling) => {
    setCookie('key', 'somos404');
    setbtnAcceptState(false)
  }

  const cancelFuncion = () => {
    setBtnCancel(false);
    setbtnAcceptState(false)

  }

useEffect(() => {
  getCokkie();
}, [])


  return (
    <>
     
      <Layout data-scroll-section>
     
        <Head>
          <title>404 - Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo_2 (1).ico" />
        </Head>
       
        <Hero />
        {btnAcceptState && (
                <div className={`${hero["containerCookies"]} `} style={{ position: 'absolute', width: '800px'}}>
                <div className={`${hero["hero_bottom1"]} `}>
                
        
                    <div
                      className={`${hero["hero_bottom__frame"]} ${hero["hero_bottom__frame--three"]} aspect_ratio__item object_fit_cover div-video`}
                    >
                      <div className={`${hero["hero_container_text2"]}`}>
                        <div><h1 className={`${hero["hero_text_title"]}`}  style={{ textAlign: 'center', color: 'yellow', fontWeight: '700', fontFamily: 'Helvetica' }}>WELCOME TO OUR WORLD</h1></div>
                        <div><h2 className={`${hero["hero_text_subtitle"]}`}  style={{ textAlign: 'center',  fontWeight: '700',fontFamily: 'Helvetica'}}>AVISO DE COOKIES</h2></div>
                      </div>
                      <span className={hero["hero_container_btn"]} style={{ display: 'flex', justifyContent: ' center' }}>
                        <button
                        className={`${hero["hero_btn_ok"]}`}
                        style={{ border: "none", color: 'blue', fontWeight: '700', marginLeft: "0px", cursor: 'pointer'}}
                        onClick={aceptFunction}>OK</button>
                        <button 
                        style={{ border: "none", color: 'blue', fontWeight: '700', cursor: 'pointer'}}
                        className={`${hero["hero_btn_cancel"]}`}
                        onClick={cancelFuncion}
                        >CANCEL
                        </button>
                      </span>
                      <div>
          
                        <video
                      src="/cookies.mp4"
                      className={hero["hero_video__containerCokies"]}
                      autoPlay
                      ref={ref}
                    >
                      <source src="/cookies.mp4" type="video/mp4"></source>
                    </video>
                      </div>
                    </div>
                  </div>
                </div>
           )}
    
     
        <ProyectList />
        <Services />
        <About />
        <Blend />
        <People />
        
        

      </Layout>
    </>
  );
}

export default Home;
