import LoginModal from '../src/Components/Login'
import hero from "./styles.module.scss";
import Layout from "../src/Components/Layout/Layout";
import Head from "next/head";

const Login = () => {
  return (
 <div>
     
     <Head>
       <title>404 - Login</title>
       <meta name="description" content="Generated by somos404" />
       <link rel="icon" href="/logo_2 (1).ico" />
     </Head>
   <LoginModal /> 

 </div>
 
  
  )
}

export default Login;